groups:
  - name: multivm_alerts
    interval: 30s
    rules:
      # Node Health Alerts
      - alert: NodeDown
        expr: up{job="multivm"} == 0
        for: 2m
        labels:
          severity: critical
          service: multivm
        annotations:
          summary: "MultiVM node {{ $labels.instance }} is down"
          description: "MultiVM node {{ $labels.instance }} has been down for more than 2 minutes."

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 85% (current value: {{ $value }})"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 85% (current value: {{ $value }})"

      # Blockchain Alerts
      - alert: BlockProductionStopped
        expr: rate(multivm_blocks_total[5m]) == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Block production has stopped"
          description: "No new blocks have been produced in the last 2 minutes"

      - alert: LowPeerCount
        expr: multivm_peers_connected < 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low peer count on {{ $labels.instance }}"
          description: "Connected peers: {{ $value }}"

      - alert: ConsensusFailure
        expr: multivm_consensus_failures_total > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Consensus failure detected"
          description: "Consensus failures: {{ $value }}"

      # API Alerts
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(multivm_api_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API latency"
          description: "95th percentile API latency is above 1 second"

      - alert: HighErrorRate
        expr: rate(multivm_api_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API error rate"
          description: "API error rate is above 5%"

      # Disk Space Alerts
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is below 10% ({{ $value }}% remaining)"

      # Transaction Pool Alerts
      - alert: TransactionPoolFull
        expr: multivm_txpool_pending_transactions > 10000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Transaction pool is getting full"
          description: "Pending transactions: {{ $value }}"

      # Network Alerts
      - alert: HighNetworkLatency
        expr: multivm_p2p_latency_seconds > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High network latency between nodes"
          description: "P2P latency is above 500ms"