global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'multivm-production'
    monitor: 'prometheus'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules files
rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:
  # MultiVM metrics
  - job_name: 'multivm'
    static_configs:
      - targets:
          - multivm-node1-prod:9000
          - multivm-node2-prod:9000
          - multivm-node3-prod:9000
        labels:
          service: 'multivm'
    
  # Reth metrics
  - job_name: 'reth'
    static_configs:
      - targets:
          - multivm-node1-prod:9001
          - multivm-node2-prod:9001
          - multivm-node3-prod:9001
        labels:
          service: 'reth'
          
  # Solana metrics
  - job_name: 'solana'
    static_configs:
      - targets:
          - multivm-node1-prod:9002
          - multivm-node2-prod:9002
          - multivm-node3-prod:9002
        labels:
          service: 'solana'
          
  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets:
          - nginx-exporter:9113
        labels:
          service: 'nginx'
          
  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets:
          - node-exporter-node1:9100
          - node-exporter-node2:9100
          - node-exporter-node3:9100
        labels:
          service: 'system'
          
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alert rules
# Create separate files in /etc/prometheus/rules/